trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: git checkout $(Build.SourceBranch)
  displayName: 'Checkout Code'
  
- task: UseNode@1
  inputs:
    version: '14.x'

- script: npm install
  displayName: 'Install Dependencies'

- script: npm test
  displayName: 'Run Tests'

- script: npm run build
  displayName: 'Build the Project'
